"""Hinglish (Roman Hindi) versions of the main tools. Same tools, copy written for how people search in India."""

H2_HOW = "Kaise kaam karta hai"
H2_FAQ = "Aksar pooche jaane wale sawal"

HI_PAGES = [
    dict(path="/hi/instagram-reel-download", engine="ig", nav=None, ph="Instagram reel ka link yahan paste karo",
         title="Instagram Reel Download Kaise Kare (Free) | MaxDownloader",
         desc="Instagram reel download kaise kare? Reel ka link paste karo aur MP4 me free save karo. Koi app ya login nahi chahiye. Phone aur PC par chalta hai.",
         h1="Instagram Reel Download Kaise Kare",
         lede="Reel ka link paste karo aur MP4 video apne phone ya PC me save karo. Free hai, login nahi chahiye.",
         intro="Instagram par kayi reels par download ka button nahi hota. Yahan reel ka link paste karo aur hum video ki file nikal dete hain. Sirf public reels download hoti hain, aur sirf wahi download karo jo tumhari apni ho ya jiski tumhe permission ho.",
         steps=[("Reel ka link copy karo", "Instagram me reel par Share dabao aur 'Copy link' chuno."),
                ("Yahan paste karo", "Link ko upar ke box me paste karo aur 'Get media' dabao."),
                ("Download dabao", "Reel ka preview aayega. Download dabao, video MP4 me save ho jayegi.")],
         faq=[("Kya reel download karne ke liye login chahiye?", "Nahi. Apna Instagram account dene ki zaroorat nahi hai."),
              ("Kya private account ki reel download hogi?", "Nahi, sirf public reels."),
              ("Phone me reel kahan save hoti hai?", "Android me Downloads folder me aur gallery me. iPhone par pehle Files app ke Downloads me aati hai."),
              ("Tool kabhi nahi chale to?", "Instagram kabhi-kabhi servers ko limit kar deta hai. 5 se 10 minute baad dobara try karo.")]),
    dict(path="/hi/instagram-dp-download", engine="ig", nav=None, ph="Username ya profile link yahan paste karo",
         title="Instagram DP Download Kaise Kare (Full Size) | MaxDownloader",
         desc="Instagram DP full size me dekho aur download karo. Username ya profile link daalo, bada profile picture save karo. Free aur bina login.",
         h1="Instagram DP Download Kaise Kare",
         lede="Username ya profile link daalo aur DP ko uski sabse badi size me dekho aur save karo.",
         intro="Instagram app me DP sirf thodi si badi hoti hai aur save nahi hoti. Yahan tum use badi size me dekh aur download kar sakte ho. Card par size bhi likhi aati hai, jaise 1080x1080.",
         steps=[("Username copy karo", "Profile ka username ya profile link copy karo."),
                ("Yahan paste karo", "Upar ke box me paste karo aur 'Get media' dabao."),
                ("Download ya View full size", "Badi DP ka preview dikhega. Download se save karo ya 'View full size' se poori photo dekho.")],
         faq=[("Kya DP dekhne par us account ko pata chalta hai?", "Instagram DP dekhne par koi notification nahi bhejta."),
              ("DP chhoti kyun aati hai?", "Size Instagram par depend karti hai. Kuch purane accounts ki DP asal me hi chhoti hoti hai."),
              ("Kya private account ki DP milti hai?", "Aksar mil jati hai kyunki DP sabko dikhti hai, par kabhi-kabhi nahi bhi milti."),
              ("Kya login chahiye?", "Nahi.")]),
    dict(path="/hi/instagram-story-download", engine="ig", nav=None, mode="story", ph="Username ya story ka link yahan paste karo",
         title="Instagram Story Download Kaise Kare | MaxDownloader",
         desc="Instagram story ko photo ya video me download karo. Username daalo aur public account ki active stories save karo. Free, bina app.",
         h1="Instagram Story Download Kaise Kare",
         lede="Username ya story ka link daalo aur us account ki active stories save karo.",
         intro="Story 24 ghante me hat jati hai, isliye use jaldi save karna padta hai. Yahan har active story alag card me aati hai, photo JPG me aur video MP4 me. Sirf public account ki stories chalti hain, aur highlights abhi nahi.",
         steps=[("Username copy karo", "Jis account ki story chahiye uska username copy karo."),
                ("Yahan paste karo", "Upar ke box me paste karo aur 'Get media' dabao."),
                ("Story download karo", "Har story ke card par Download dabao.")],
         faq=[("Kya owner ko pata chalta hai ki maine download ki?", "Download ka pata nahi chalta. Lekin stories hamare server ke ek account se fetch hoti hain, isliye us account ka naam viewers ki list me aa sakta hai."),
              ("Private account ki story aayegi?", "Nahi."),
              ("Highlights download hongi?", "Abhi nahi, sirf active stories."),
              ("'No active stories' kyun likha aata hai?", "Us account ne abhi koi story nahi lagayi, ya account private hai.")]),
    dict(path="/hi/youtube-video-download", engine="yt", fmt="mp4", nav=None,
         title="YouTube Video Download Kaise Kare (MP4) | MaxDownloader",
         desc="YouTube video ko MP4 me download kaise kare? Link paste karo, quality chuno aur save karo. Free hai, phone aur PC par chalta hai.",
         h1="YouTube Video Download Kaise Kare",
         lede="YouTube video ka link paste karo, quality chuno aur MP4 me download karo. Free aur bina sign-up.",
         intro="Yahan YouTube video ka link paste karke tum use MP4 file me save kar sakte ho. Sirf wahi video download karo jo tumhari apni ho, Creative Commons ki ho ya jiski tumhe permission ho.",
         steps=[("Video ka link copy karo", "YouTube me Share dabao aur Copy link chuno."),
                ("Link paste karo", "Upar ke box me paste karo aur 'Get video' dabao."),
                ("Quality chuno aur download karo", "360p sabse tez aati hai. Phir Download dabao.")],
         bullets=["Koi account ya sign-up nahi.", "MP4 video, jitni quality video me hai (4K tak).", "Awaaz ke saath video aati hai.", "Phone aur PC dono par chalta hai."],
         faq=[("Kya YouTube video download karna free hai?", "Haan, yahan koi charge nahi hai."),
              ("Video jaldi kaise aaye?", "360p chuno. File chhoti hoti hai aur jaldi aati hai."),
              ("Kya playlist download hoti hai?", "Abhi nahi, sirf ek normal video."),
              ("Kya ye legal hai?", "Ye video par depend karta hai. Apni video ya permission wali video hi download karo.")]),
    dict(path="/hi/youtube-to-mp3", engine="yt", fmt="mp3", nav=None,
         title="YouTube Video Ko MP3 Me Convert Kare | MaxDownloader",
         desc="YouTube video ko MP3 audio me convert karo. Link paste karo aur 192 kbps MP3 file download karo. Free, bina sign-up, phone aur PC par.",
         h1="YouTube Video Ko MP3 Me Convert Kare",
         lede="Link paste karo aur YouTube video ki awaaz MP3 file me save karo.",
         intro="Lecture, podcast ya apni khud ki recording sunne ke liye MP3 bahut kaam aati hai. Yahan video ka link paste karo aur 192 kbps MP3 file download karo. Sirf wahi audio convert karo jiske rights tumhare paas hon.",
         steps=[("Link copy karo", "YouTube video ka link copy karo."),
                ("Link paste karo", "Upar ke box me paste karo aur 'Get video' dabao."),
                ("MP3 download karo", "Format pehle se MP3 chuna hota hai. Download dabao.")],
         bullets=["Koi account ya sign-up nahi.", "MP3 audio 192 kbps me.", "Phone aur PC dono par chalta hai.", "Temporary file download ke baad delete ho jati hai."],
         faq=[("MP3 ki quality kitni hoti hai?", "192 kbps, roz ke sunne ke liye theek."),
              ("Kya MP3 me video bhi aati hai?", "Nahi, sirf awaaz."),
              ("MP3 phone me kahan milegi?", "Android me Downloads folder me. iPhone par Files app me."),
              ("Kya gaane convert kar sakte hain?", "Sirf wahi jiske rights ya permission tumhare paas ho.")]),
    dict(path="/hi/pinterest-video-download", engine="pin", nav=None,
         title="Pinterest Video Download Kaise Kare (HD) | MaxDownloader",
         desc="Pinterest ki video, photo aur GIF ko original quality me download karo. Pin ka link paste karo, pin.it bhi chalta hai. Free, bina login.",
         h1="Pinterest Video Download Kaise Kare",
         lede="Pin ka link paste karo aur video, photo ya GIF ko original quality me save karo.",
         intro="Pinterest par zyadatar pins ke saath download ka button nahi hota. Yahan pin ka link paste karo, hum video ko MP4 me, photo ko badi size me aur GIF ko .gif file me nikal dete hain. Pins creators ki hoti hain, isliye aage post karne se pehle permission lo.",
         steps=[("Pin ka link copy karo", "Pin par Share dabao aur link copy karo. pin.it link bhi chalta hai."),
                ("Link paste karo", "Upar ke box me paste karo (ek saath 20 tak) aur 'Find media' dabao."),
                ("Download dabao", "Har pin ka alag card aayega. Download dabao.")],
         faq=[("Kya pin.it wale links chalte hain?", "Haan."),
              ("Kya ek saath kayi pins download ho sakti hain?", "Haan, 20 tak links ek saath paste karo."),
              ("Kya private pins download hoti hain?", "Nahi, sirf public pins."),
              ("GIF kaise milegi?", "Agar pin GIF hai to card par GIF likha aayega aur wo .gif file me download hogi.")]),
]
for _p in HI_PAGES:
    _p["lang"] = "hi-Latn"
    _p["h2_how"] = H2_HOW
    _p["h2_faq"] = H2_FAQ
